### ISSUE TITLE
Automatically strip https:// from host str if it starts with that

### ISSUE THREAD

**Issue by iver56** [vangorra/python_gogogate2_api#22]
I accidentally included `https://` in the host string, while ISmartGateApi apparently did not expect that.

```
ismartgate_api = ISmartGateApi(
    "https://xxxxxxxxxx.isgaccess.com", "thatusername", "thatpassword"
)
```

This resulted in an error like "ConnectError: [Errno 11001] getaddrinfo failed"

Perhaps `ISmartGateApi.__init__` could automatically strip away http:// and https:// if the host starts with that? Or emit a warning? Or maybe an exception with a helpful message saying that the http:// / https:// part should be excluded from the string?

**Comment by vangorra** [comment]
The developer is the authoritative source of input. When a developer says "do X" but the code "does Y", despite the similarity, this results in numerous issues. Additionally, adding extra code to guess if the developer made a mistake creates unnecessary tech-debt. If the dev provided a value, then we should use that value. Questioning/modification of user input is relegated to the interactive user interface layer.
