### ISSUE TITLE
Question: why are you using pycryptodomex?

### ISSUE THREAD

**Issue by onkelbeh** [vangorra/python_gogogate2_api#6]
Hi,

may I ask:
why are you using pycryptodomex and not pycryptodome?

When I walk through Home Assitants dependecy tree, I find 14 packages using pycryptodome, and 2 (including you) requiring pycryptodomex. Both libraries install themselves as pycryptodome. This results in a slot conflict.

**Comment by onkelbeh** [comment]
Hi, just check again, cause by the conflict.
Unfortunaltely I don't own own any of these devices, so I can't do a real test.
But I can run all software tests successful with pycryptodome-3.9.8

Here are my ebuild for your component, could you take a look at the dependencies, please?
https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/gogogate2-api

**Comment by vangorra** [comment]
No good reason. I was planning to switch it out but forgot. I'll prioritize the change.

**Comment by onkelbeh** [comment]
OK, thanks.
